name: Pack
on:
  push:
    branches: [lib]
  workflow_dispatch:
env:
  BUILD: Travel Earth Plan
  VERSION: Build Edition v


jobs:
  CreateCursePack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run run/build.sh
        run: bash run/build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD }}-${{ env.VERSION }}.${{ github.run_number }}
          path: artifacts
